# Generated by Django 5.2.1 on 2025-07-06 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0003_alter_user_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('name', models.CharField(max_length=210, unique=True)),
                ('slug', models.SlugField(max_length=210, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField()),
                ('price_per_day', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Subscription plan',
                'verbose_name_plural': 'Subscription plans',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_subscription', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('status', models.CharField(choices=[('AC', 'فعال'), ('IN', 'غیر فعال')], default='IN', max_length=2)),
                ('duration', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='plans_subscriptions', to='Subscriptions.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'unique_together': {('user', 'plan')},
            },
        ),
    ]
