# Generated by Django 5.2.1 on 2025-07-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
