# Generated by Django 5.2.1 on 2025-07-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscriptions', '0002_subscriptionplan_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='Subsciptions/plans/icons/'),
        ),
    ]
