import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Theme from "@/providers/ThemeProvider";



export const metadata: Metadata = {
  title: "codingo plus",
  description: "Generated by mobin heydari",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" suppressHydrationWarning>
      <body className="dark:bg-base-dark bg-base-light">
        <Theme>
          <Navbar />
          {children}
        </Theme>
      </body>
    </html>
  );
}
