import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "codingo plus",
  description: "Generated by mobin heydari",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className="">
        {children}
      </body>
    </html>
  );
}
