// app/layout.tsx (still server)
import type { Metadata } from "next";

import "./globals.css";

import ClientProviders from "@/providers/ClientProviders";

import { getServerSession } from "next-auth";

import { authOptions } from "./api/auth/[...nextauth]/route";



export const metadata: Metadata = {
  title: "codingo plus",
  description: "Generated by mobin heydari",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="fa" dir="rtl" suppressHydrationWarning>
      <body className="dark:bg-base-dark bg-base-light font-custom">
        <ClientProviders session={session}>
          {children}
        </ClientProviders>
      </body>
    </html>
  );
}
