# Generated by Django 5.2.1 on 2025-06-13 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Otps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegisterOneTimePassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=128)),
                ('full_name', models.CharField(max_length=255)),
                ('password_conf', models.CharField(max_length=255)),
                ('user_type', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('otp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_otps', to='Otps.onetimepassword')),
            ],
            options={
                'verbose_name': 'User Register otp',
                'verbose_name_plural': '',
            },
        ),
    ]
