# Generated by Django 5.2.1 on 2025-07-19 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carts', '0003_cart'),
        ('Courses', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت دوره')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_items', to='Carts.cart', verbose_name='سبد خرید')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.course', verbose_name='دوره')),
            ],
            options={
                'verbose_name': 'آیتم سبد خرید',
                'verbose_name_plural': 'آیتم های سبد خرید',
                'unique_together': {('cart', 'course')},
            },
        ),
    ]
