# Generated by Django 5.2.1 on 2025-07-24 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carts', '0004_courseitem'),
        ('Coupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Coupons.coupon', verbose_name='کوپن تخفیف'),
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
