# Generated by Django 5.2.1 on 2025-08-08 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carts', '0005_alter_cart_coupon_delete_coupon'),
        ('Discounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Discounts.coupon', verbose_name='کوپن تخفیف'),
        ),
    ]
