# Generated by Django 5.2.1 on 2025-07-05 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Podcasts', '0002_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='عنوان پادکست')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('presenter', models.CharField(blank=True, max_length=100, null=True, verbose_name='گوینده پادکست')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Podcasts/images/', verbose_name='تصویر پادکست')),
                ('file', models.FileField(blank=True, null=True, upload_to='Podcasts/files/', verbose_name='فایل')),
                ('audio', models.FileField(blank=True, null=True, upload_to='Podcasts/audios/', verbose_name='فایل صوتی')),
                ('video', models.FileField(blank=True, null=True, upload_to='Podcasts/videos/', verbose_name='ویدیو ها')),
                ('payment_status', models.CharField(choices=[('F', 'رایگان'), ('S', 'اشتراکی')], default='S', max_length=1)),
                ('type_status', models.CharField(choices=[('A', 'ضوتی'), ('V', 'ویدیو'), ('B', 'هردو')], default='A', max_length=1)),
                ('language', models.CharField(choices=[('FA', 'فارسی'), ('EN', 'انگلیسی')], default='FA', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'پادکست',
                'verbose_name_plural': 'پادکست ها',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان برچسب')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='نامک')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب ها',
                'ordering': ['title'],
            },
        ),
    ]
