# Generated by Django 5.2.1 on 2025-07-05 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Podcasts', '0003_podcast_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Podcast',
        ),
    ]
