# Generated by Django 5.2.1 on 2025-06-13 09:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimePassword',
            fields=[
                ('status', models.CharField(choices=[('EXP', 'Expired'), ('ACT', 'Active'), ('USE', 'Used')], default='ACT', max_length=3)),
                ('token', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='توکن')),
                ('code', models.CharField(max_length=6)),
                ('expiration', models.DateTimeField(blank=True, null=True)),
                ('is_used', models.BooleanField(default=False, verbose_name='استفاده شده؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'رمز یکبار مصرف',
                'verbose_name_plural': 'رمز های یکبار مصرف',
            },
        ),
    ]
