# Generated by Django 5.2.1 on 2025-07-04 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان دسته بندی')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='نامک')),
                ('icon', models.FileField(upload_to='Books/SubCategory_icons/', verbose_name='آیکون')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_subcategories', to='Books.maincategory', verbose_name='دسته بندی والد')),
            ],
            options={
                'verbose_name': 'زیر دسته بندی',
                'verbose_name_plural': 'زیر دسته بندی ها',
                'ordering': ['title'],
            },
        ),
    ]
