# Generated by Django 5.2.1 on 2025-07-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='عنوان کتاب')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('author', models.CharField(max_length=200, unique=True, verbose_name='نویسنده کتاب')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Books/images/', verbose_name='تصویر کتاب')),
                ('file', models.FileField(upload_to='Books/files/', verbose_name='فایل')),
                ('payment_status', models.CharField(choices=[('F', 'رایگان'), ('S', 'اشتراکی')], default='S', max_length=1)),
                ('language', models.CharField(choices=[('FA', 'فارسی'), ('EN', 'انگلیسی')], default='FA', max_length=2)),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'کتاب',
                'verbose_name_plural': 'کتاب ها',
            },
        ),
    ]
