# Generated by Django 5.2.1 on 2025-07-04 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0004_books'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
