# Generated by Django 5.2.1 on 2025-07-17 07:19

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان پست')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='نامک')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='توضیحات')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='Blogs/posters/', verbose_name='پوستر پست')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='Blogs/banners/', verbose_name='بنر پست')),
                ('status', models.CharField(choices=[('DR', 'پیش نویس شود'), ('PD', 'منتشر شود')], default='DR', max_length=10, verbose_name='وضعیت')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='بازدید ها')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'پست بلاگ',
                'verbose_name_plural': 'پست های بلاگ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان بخش')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='متن بخش')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blogs/content_images/', verbose_name='تصویر بخش')),
                ('video', models.URLField(blank=True, null=True, verbose_name='ویدیو بخش')),
                ('link', models.URLField(blank=True, null=True, verbose_name='لینک مرتبط')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'بخش محتوا',
                'verbose_name_plural': 'بخش\u200cهای محتوا',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='نظر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('approved', models.BooleanField(default=False, verbose_name='تایید شده')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='نظر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('approved', models.BooleanField(default=False, verbose_name='تایید شده')),
            ],
            options={
                'verbose_name': 'ریپلای',
                'verbose_name_plural': 'ریپلای ها',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان دسته بندی')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='نامک')),
                ('icon', models.FileField(upload_to='Blogs/MainCategory_icons/', verbose_name='آیکون')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'دسته بندی والد',
                'verbose_name_plural': 'دسته بندی های والد',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان دسته بندی')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='نامک')),
                ('icon', models.FileField(upload_to='Blogs/SubCategory_icons/', verbose_name='آیکون')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'زیر دسته بندی',
                'verbose_name_plural': 'زیر دسته بندی ها',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان برچسب')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='نامک')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب ها',
                'ordering': ['title'],
            },
        ),
    ]
