# Generated by Django 5.2.1 on 2025-06-05 00:50

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0003_tag_alter_subcategory_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان پست')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='نامک')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='توضیحات')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='Blogs/posters/', verbose_name='پوستر پست')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='Blogs/banners/', verbose_name='بنر پست')),
                ('status', models.CharField(choices=[('DR', 'پیش نویس شود'), ('PD', 'منتشر شود')], default='DR', max_length=10, verbose_name='وضعیت')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='بازدید ها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده پست')),
                ('category', models.ManyToManyField(related_name='blogs', to='Blogs.subcategory', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'پست بلاگ',
                'verbose_name_plural': 'پست های بلاگ',
            },
        ),
    ]
