# Generated by Django 5.2.1 on 2025-06-05 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0004_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='Blogs.tag', verbose_name='برچسب'),
        ),
    ]
