# Generated by Django 5.2.1 on 2025-06-05 20:06

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0008_rename_blogpost_blog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at'], 'verbose_name': 'پست بلاگ', 'verbose_name_plural': 'پست های بلاگ'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
        migrations.AlterModelOptions(
            name='commentreply',
            options={'ordering': ['created_at'], 'verbose_name': 'ریپلای', 'verbose_name_plural': 'ریپلای ها'},
        ),
        migrations.AlterModelOptions(
            name='maincategory',
            options={'ordering': ['title'], 'verbose_name': 'دسته بندی والد', 'verbose_name_plural': 'دسته بندی های والد'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['title'], 'verbose_name': 'زیر دسته بندی', 'verbose_name_plural': 'زیر دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['title'], 'verbose_name': 'برچسب', 'verbose_name_plural': 'برچسب ها'},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='blog_post',
        ),
        migrations.AddField(
            model_name='blog',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار'),
        ),
        migrations.AddField(
            model_name='blog',
            name='sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='Blogs.subcategory', verbose_name='دسته بندی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='blogs', to='Blogs.tag', verbose_name='برچسب'),
        ),
        migrations.AddField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='تایید شده'),
        ),
        migrations.AddField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blog_comments', to='Blogs.blog', verbose_name='پست مربوطه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentreply',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='تایید شده'),
        ),
        migrations.AddField(
            model_name='maincategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='commentreply',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_replies', to='Blogs.comment', verbose_name='نظر مربوطه'),
        ),
        migrations.AlterField(
            model_name='commentreply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment_replies', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='icon',
            field=models.FileField(upload_to='Blogs/MainCategory_icons/', verbose_name='آیکون'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='icon',
            field=models.FileField(upload_to='Blogs/SubCategory_icons/', verbose_name='آیکون'),
        ),
        migrations.CreateModel(
            name='BlogContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان بخش')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='متن بخش')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blogs/content_images/', verbose_name='تصویر بخش')),
                ('video', models.URLField(blank=True, null=True, verbose_name='ویدیو بخش')),
                ('link', models.URLField(blank=True, null=True, verbose_name='لینک مرتبط')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='Blogs.blog', verbose_name='پست مربوطه')),
            ],
            options={
                'verbose_name': 'بخش محتوا',
                'verbose_name_plural': 'بخش\u200cهای محتوا',
                'ordering': ['order'],
            },
        ),
    ]
