# Generated by Django 5.2.1 on 2025-07-24 00:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد تخفیف')),
                ('discount_value', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='مقدار تخفیف (درصد)')),
                ('max_usage', models.IntegerField(blank=True, null=True, verbose_name='حداکثر استفاده')),
                ('usage_count', models.IntegerField(default=0, verbose_name='تعداد استفاده شده')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='معتبر از')),
                ('valid_to', models.DateTimeField(verbose_name='معتبر تا')),
                ('type_status', models.CharField(choices=[('EX', 'منقضی شده'), ('US', 'استفاده شده'), ('UN', 'استفاده نشده')], default='UN', max_length=2, verbose_name='وضعیت کد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('user', models.ForeignKey(blank=True, help_text='اگر خالی باشد، کد برای همه کاربران معتبر است', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر اختصاصی')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کد \u200cهای تخفیف',
            },
        ),
    ]
