# Generated by Django 5.2.1 on 2025-08-08 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={},
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='code',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='discount_value',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='max_usage',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='type_status',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='usage_count',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='user',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='valid_to',
        ),
    ]
