# Generated by Django 5.2.1 on 2025-07-10 10:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('W', 'خانوم'), ('M', 'آقا')], max_length=1, verbose_name='جنسیت')),
                ('age', models.PositiveIntegerField(default=18, verbose_name='سن')),
                ('bio', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='بیو')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='Profiles/admin/picture/', verbose_name='تصویر پروفایل')),
                ('profile_banner', models.ImageField(blank=True, null=True, upload_to='Profiles/admin/banner/', verbose_name='بنر پروفایل')),
                ('is_available', models.BooleanField(default=True, verbose_name='در دسترس بودن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'پروفایل مدیر',
                'verbose_name_plural': 'پروفایل مدیران',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('W', 'خانوم'), ('M', 'آقا')], max_length=1, verbose_name='جنسیت')),
                ('age', models.PositiveIntegerField(default=18, verbose_name='سن')),
                ('bio', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='بیو')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='Profiles/students/picture/', verbose_name='تصویر پروفایل')),
                ('profile_banner', models.ImageField(blank=True, null=True, upload_to='Profiles/students/banner/', verbose_name='بنر پروفایل')),
                ('is_available', models.BooleanField(default=True, verbose_name='در دسترس بودن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'پروفایل دانشجو',
                'verbose_name_plural': 'پروفایل دانشجویان',
            },
        ),
        migrations.CreateModel(
            name='SupporterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('W', 'خانوم'), ('M', 'آقا')], max_length=1, verbose_name='جنسیت')),
                ('age', models.PositiveIntegerField(default=18, verbose_name='سن')),
                ('bio', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='بیو')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='Profiles/supporters/picture/', verbose_name='تصویر پروفایل')),
                ('profile_banner', models.ImageField(blank=True, null=True, upload_to='Profiles/supporters/banner/', verbose_name='بنر پروفایل')),
                ('is_available', models.BooleanField(default=True, verbose_name='در دسترس بودن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'پروفایل پشتیبان',
                'verbose_name_plural': 'پروفایل پشتیبان ها',
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('W', 'خانوم'), ('M', 'آقا')], max_length=1, verbose_name='جنسیت')),
                ('age', models.PositiveIntegerField(default=18, verbose_name='سن')),
                ('bio', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='بیو')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='Profiles/teachers/picture/', verbose_name='تصویر پروفایل')),
                ('profile_banner', models.ImageField(blank=True, null=True, upload_to='Profiles/teachers/banner/', verbose_name='بنر پروفایل')),
                ('is_available', models.BooleanField(default=True, verbose_name='در دسترس بودن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'پروفایل استاد',
                'verbose_name_plural': 'پروفایل اساتید',
            },
        ),
    ]
