# Generated by Django 5.2.1 on 2025-05-30 09:09

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('W', 'خانوم'), ('M', 'آقا')], max_length=1, verbose_name='جنسیت')),
                ('age', models.PositiveIntegerField(default=18, verbose_name='سن')),
                ('bio', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='بیو')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='Profiles/teachers/picture/', verbose_name='تصویر پروفایل')),
                ('profile_banner', models.ImageField(blank=True, null=True, upload_to='Profiles/teachers/banner/', verbose_name='بنر پروفایل')),
                ('is_available', models.BooleanField(default=True, verbose_name='در دسترس بودن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل استاد',
                'verbose_name_plural': 'پروفایل اساتید',
            },
        ),
    ]
