# Generated by Django 5.2.1 on 2025-07-17 07:19

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='نظر')),
                ('popular_comment', models.BooleanField(default=False, verbose_name='نظر برگزیده')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='تعداد لایک')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
            },
        ),
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='پاسخ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'پاسخ',
                'verbose_name_plural': 'پاسخ\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('F', 'رایگان'), ('P', 'پولی')], default='P', max_length=1)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='courses/posters/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='courses/banners/')),
                ('trailer', models.FileField(blank=True, null=True, upload_to='courses/trailers/')),
                ('language', models.CharField(choices=[('FA', 'فارسی'), ('EN', 'انگلیسی')], default='FA', max_length=2)),
                ('level_status', models.CharField(choices=[('IN', 'مقدمه\u200cای'), ('IM', 'متوسط'), ('AD', 'پیشرفته'), ('IA', 'مقدماتی تا پیشرفته')], default='IN', max_length=2)),
                ('status', models.CharField(choices=[('C', 'تکمیل شده'), ('I', 'درحال برگزاری'), ('S', 'شروع به زودی')], default='S', max_length=2)),
                ('publish_status', models.CharField(choices=[('DR', 'پیش نویس'), ('PD', 'منتشر شده')], default='DR', max_length=2)),
                ('views', models.PositiveIntegerField(default=0)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='عنوان فصل')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات فصل')),
                ('duration', models.DurationField(default=datetime.timedelta(0), verbose_name='مدت زمان فصل')),
                ('order', models.PositiveIntegerField(verbose_name='ترتیب فصل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'فصل',
                'verbose_name_plural': 'فصول',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب محتوا')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان محتوا')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='توضیحات محتوا')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Courses/content/images/', verbose_name='تصویر محتوا')),
                ('video', models.FileField(blank=True, null=True, upload_to='Courses/content/videos/', verbose_name='ویدیو محتوا')),
                ('attachments', models.FileField(blank=True, null=True, upload_to='Courses/content/attachments/', verbose_name='فایل ضمیمه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'محتوای دوره',
                'verbose_name_plural': 'محتواهای دوره',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CourseFaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100, verbose_name='سوال')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'سوال متداول',
                'verbose_name_plural': 'سوالات متداول',
            },
        ),
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='عنوان جلسه')),
                ('video', models.FileField(upload_to='Courses/sessions/videos/', verbose_name='ویدیو جلسه')),
                ('file_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک فایل درسی')),
                ('resources', models.FileField(blank=True, null=True, upload_to='Courses/sessions/resources/', verbose_name='منابع پیوست')),
                ('order', models.PositiveIntegerField(verbose_name='ترتیب جلسه')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پولی؟')),
                ('is_preview', models.BooleanField(default=False, verbose_name='پیش\u200cنمایش؟')),
                ('duration', models.DurationField(default=datetime.timedelta(0), verbose_name='مدت زمان جلسه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'جلسه',
                'verbose_name_plural': 'جلسات',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان دسته بندی')),
                ('slug', models.SlugField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='نامک')),
                ('icon', models.FileField(upload_to='courses/main_category/icons/', verbose_name='آیکون دسته بندی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'دسته بندی والد',
                'verbose_name_plural': 'دسته بندی های والد',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان دسته بندی')),
                ('slug', models.SlugField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='نامک')),
                ('icon', models.FileField(upload_to='courses/sub_category/icons/', verbose_name='آیکون زیر دسته بندی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'زیر دسته بندی',
                'verbose_name_plural': 'زیر دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='برچسب')),
                ('slug', models.SlugField(unique=True, verbose_name='نامک برچسب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب\u200cها',
            },
        ),
    ]
