# Generated by Django 5.2.1 on 2025-07-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='courses', to='Courses.tag'),
        ),
    ]
