# Generated by Django 5.2.1 on 2025-07-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0003_alter_course_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='publish_status',
            field=models.CharField(choices=[('DR', 'پیش نویس'), ('PD', 'منتشر شده')], default='DR', max_length=2),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('C', 'تکمیل شده'), ('I', 'درحال برگزاری'), ('S', 'شروع به زودی')], default='S', max_length=2),
        ),
    ]
