# Generated by Django 5.2.1 on 2025-07-11 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0004_course_publish_status_alter_course_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_status',
        ),
        migrations.RemoveField(
            model_name='course',
            name='enrollment_count',
        ),
        migrations.RemoveField(
            model_name='course',
            name='has_certificate',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_recommended',
        ),
        migrations.RemoveField(
            model_name='course',
            name='learning_outcomes',
        ),
        migrations.RemoveField(
            model_name='course',
            name='prerequisites',
        ),
        migrations.RemoveField(
            model_name='course',
            name='review_count',
        ),
        migrations.RemoveField(
            model_name='course',
            name='short_description',
        ),
    ]
