# Generated by Django 5.2.1 on 2025-06-02 06:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0005_coursefaq'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='عنوان فصل')),
                ('duration', models.DurationField(default=datetime.timedelta(0), verbose_name='مدت زمان')),
                ('order', models.PositiveIntegerField(verbose_name='ترتیب فصل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.course', verbose_name='دوره مربوطه')),
            ],
            options={
                'verbose_name': 'فصل',
                'verbose_name_plural': 'فصل ها',
                'ordering': ['order'],
            },
        ),
    ]
