# Generated by Django 5.2.1 on 2025-07-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0005_remove_course_average_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='parent',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='maincategory',
            name='color_code',
        ),
        migrations.RemoveField(
            model_name='maincategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='description',
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='icon',
            field=models.FileField(upload_to='courses/main_category/icons/', verbose_name='آیکون دسته بندی'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='icon',
            field=models.FileField(upload_to='courses/sub_category/icons/', verbose_name='آیکون زیر دسته بندی'),
        ),
    ]
