# Generated by Django 5.2.1 on 2025-07-13 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0006_rename_parent_subcategory_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='category',
            new_name='main_category',
        ),
    ]
