# Generated by Django 5.2.1 on 2025-06-02 06:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0006_coursechapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='عنوان ویدیو')),
                ('video_link', models.FileField(upload_to='Courses/Sessions/video', verbose_name='ویدیو')),
                ('file_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک فایل')),
                ('order', models.PositiveIntegerField(verbose_name='ترتیب ویدیو')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پولیه؟')),
                ('duration', models.DurationField(default=datetime.timedelta(0), verbose_name='مدت زمان ویدیو')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.coursechapter', verbose_name='فصل مربوطه')),
            ],
            options={
                'verbose_name': 'جلسه',
                'verbose_name_plural': 'جلسات',
                'ordering': ['order'],
            },
        ),
    ]
