# Generated by Django 5.2.1 on 2025-06-05 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0009_commentreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategory',
            name='icon',
            field=models.FileField(upload_to='Courses/SubCategory_icons/'),
        ),
    ]
