# Generated by Django 5.2.1 on 2025-06-05 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0010_alter_maincategory_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='icon',
            field=models.FileField(upload_to='Courses/SubCategory_icons/'),
        ),
    ]
