# Generated by Django 5.2.1 on 2025-06-22 09:39

import ckeditor_uploader.fields
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0012_alter_commentreply_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='برچسب')),
                ('slug', models.SlugField(unique=True, verbose_name='نامک برچسب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب\u200cها',
            },
        ),
        migrations.AlterModelOptions(
            name='commentreply',
            options={'verbose_name': 'پاسخ', 'verbose_name_plural': 'پاسخ\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'دوره', 'verbose_name_plural': 'دوره\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='coursechapter',
            options={'ordering': ['order'], 'verbose_name': 'فصل', 'verbose_name_plural': 'فصول'},
        ),
        migrations.AlterModelOptions(
            name='coursecontent',
            options={'ordering': ['order'], 'verbose_name': 'محتوای دوره', 'verbose_name_plural': 'محتواهای دوره'},
        ),
        migrations.RemoveField(
            model_name='coursesession',
            name='video_link',
        ),
        migrations.AddField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد لایک'),
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی'),
        ),
        migrations.AddField(
            model_name='commentreply',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی'),
        ),
        migrations.AddField(
            model_name='course',
            name='average_rating',
            field=models.FloatField(default=0.0, verbose_name='میانگین امتیاز'),
        ),
        migrations.AddField(
            model_name='course',
            name='enrollment_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد ثبت نام کنندگان'),
        ),
        migrations.AddField(
            model_name='course',
            name='has_certificate',
            field=models.BooleanField(default=False, verbose_name='دارای گواهی پایان دوره؟'),
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('FA', 'فارسی'), ('EN', 'انگلیسی')], default='FA', max_length=10, verbose_name='زبان دوره'),
        ),
        migrations.AddField(
            model_name='course',
            name='learning_outcomes',
            field=models.TextField(blank=True, null=True, verbose_name='اهداف یادگیری'),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.TextField(blank=True, null=True, verbose_name='پیش نیازها'),
        ),
        migrations.AddField(
            model_name='course',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار'),
        ),
        migrations.AddField(
            model_name='course',
            name='review_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد نظرات'),
        ),
        migrations.AddField(
            model_name='course',
            name='short_description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='توضیح کوتاه دوره'),
        ),
        migrations.AddField(
            model_name='course',
            name='trailer',
            field=models.FileField(blank=True, null=True, upload_to='Courses/trailers/', verbose_name='ویدیو معرفی'),
        ),
        migrations.AddField(
            model_name='coursechapter',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات فصل'),
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='Courses/content/attachments/', verbose_name='فایل ضمیمه'),
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='Courses.course', verbose_name='دوره مرتبط'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب محتوا'),
        ),
        migrations.AddField(
            model_name='coursesession',
            name='is_preview',
            field=models.BooleanField(default=False, verbose_name='پیش\u200cنمایش؟'),
        ),
        migrations.AddField(
            model_name='coursesession',
            name='resources',
            field=models.FileField(blank=True, null=True, upload_to='Courses/sessions/resources/', verbose_name='منابع پیوست'),
        ),
        migrations.AddField(
            model_name='coursesession',
            name='video',
            field=models.FileField(default=1, upload_to='Courses/sessions/videos/', verbose_name='ویدیو جلسه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maincategory',
            name='color_code',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='کد رنگ (HEX)'),
        ),
        migrations.AddField(
            model_name='maincategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات دسته بندی'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='Courses/SubCategory_banners/', verbose_name='بنر زیر دسته بندی'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات زیر دسته بندی'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='popular_comment',
            field=models.BooleanField(default=False, verbose_name='نظر برگزیده'),
        ),
        migrations.AlterField(
            model_name='commentreply',
            name='content',
            field=models.TextField(verbose_name='پاسخ'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='پیشنهادی؟'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level_status',
            field=models.CharField(choices=[('IN', 'مقدمه\u200cای'), ('IM', 'متوسط'), ('AD', 'پیشرفته'), ('IA', 'مقدماتی تا پیشرفته')], default='IN', max_length=30, verbose_name='سطح دوره'),
        ),
        migrations.AlterField(
            model_name='course',
            name='payment_status',
            field=models.CharField(choices=[('F', 'رایگان'), ('P', 'پولی')], default='P', max_length=10, verbose_name='وضعیت پرداخت دوره'),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('DR', 'پیش نویس'), ('PD', 'منتشر شده')], default='DR', max_length=10, verbose_name='وضعیت انتشار'),
        ),
        migrations.AlterField(
            model_name='course',
            name='views',
            field=models.IntegerField(default=0, verbose_name='بازدیدها'),
        ),
        migrations.AlterField(
            model_name='coursechapter',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='مدت زمان فصل'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='توضیحات محتوا'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Courses/content/images/', verbose_name='تصویر محتوا'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان محتوا'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='Courses/content/videos/', verbose_name='ویدیو محتوا'),
        ),
        migrations.AlterField(
            model_name='coursefaq',
            name='answer',
            field=models.TextField(verbose_name='پاسخ'),
        ),
        migrations.AlterField(
            model_name='coursefaq',
            name='question',
            field=models.CharField(max_length=100, verbose_name='سوال'),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='مدت زمان جلسه'),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='file_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک فایل درسی'),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='پولی؟'),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='order',
            field=models.PositiveIntegerField(verbose_name='ترتیب جلسه'),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='عنوان جلسه'),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='icon',
            field=models.FileField(upload_to='Courses/SubCategory_icons/', verbose_name='آیکون دسته بندی'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='icon',
            field=models.FileField(upload_to='Courses/SubCategory_icons/', verbose_name='آیکون زیر دسته بندی'),
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='courses', to='Courses.tag', verbose_name='برچسب\u200cها'),
        ),
    ]
