# Generated by Django 5.2.1 on 2025-06-25 13:02

import ckeditor_uploader.fields
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0013_tag_alter_commentreply_options_alter_course_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-published_date', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='course',
            name='master_note',
        ),
        migrations.AlterField(
            model_name='course',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='course',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='courses/banners/'),
        ),
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_status',
            field=models.CharField(choices=[('C', 'تکمیل شده'), ('I', 'درحال برگزاری'), ('S', 'شروع به زودی')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='course',
            name='enrollment_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='has_certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('FA', 'فارسی'), ('EN', 'انگلیسی')], default='FA', max_length=2),
        ),
        migrations.AlterField(
            model_name='course',
            name='learning_outcomes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='level_status',
            field=models.CharField(choices=[('IN', 'مقدمه\u200cای'), ('IM', 'متوسط'), ('AD', 'پیشرفته'), ('IA', 'مقدماتی تا پیشرفته')], default='IN', max_length=2),
        ),
        migrations.AlterField(
            model_name='course',
            name='payment_status',
            field=models.CharField(choices=[('F', 'رایگان'), ('P', 'پولی')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='courses/posters/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='short_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('DR', 'پیش نویس'), ('PD', 'منتشر شده')], default='DR', max_length=2),
        ),
        migrations.AlterField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='courses', to='Courses.tag'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='trailer',
            field=models.FileField(blank=True, null=True, upload_to='courses/trailers/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories_courses', to='Courses.subcategory'),
            preserve_default=False,
        ),
    ]
