# Generated by Django 5.2.1 on 2025-07-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategory',
            name='icon',
            field=models.FileField(upload_to='Articles/MainCategory_icons/', verbose_name='آیکون'),
        ),
    ]
