# Generated by Django 5.2.1 on 2025-07-02 03:54

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0005_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان مقاله')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='نامک')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='توضیحات')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='Articles/posters/', verbose_name='پوستر مقاله')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='Articles/banners/', verbose_name='بنر مقاله')),
                ('status', models.CharField(choices=[('DR', 'پیش نویس شود'), ('PD', 'منتشر شود')], default='DR', max_length=10, verbose_name='وضعیت')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='بازدید ها')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Articles.author', verbose_name='نویسنده مقاله')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='Articles.subcategory', verbose_name='دسته بندی')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='Articles.tag', verbose_name='برچسب')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-created_at'],
            },
        ),
    ]
