# Generated by Django 5.2.1 on 2025-07-02 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0006_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='Articles.subcategory', verbose_name='دسته بندی'),
        ),
    ]
