# Generated by Django 5.2.1 on 2025-07-24 07:28

import django.core.validators
import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Carts', '0005_alter_cart_coupon_delete_coupon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=10, max_length=10, prefix='', unique=True, verbose_name='شناسه سفارش')),
                ('total_price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='مجموع قیمت')),
                ('tax', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مالیات')),
                ('discount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='تخفیف')),
                ('final_price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت نهایی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='Carts.cart', verbose_name='سبد خرید مرتبط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
