# Generated by Django 5.2.1 on 2025-07-24 07:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_initial'),
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCourseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت دوره')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='Courses.course', verbose_name='دوره')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_items', to='Orders.order', verbose_name='سفارش مرتبط')),
            ],
            options={
                'verbose_name': 'آیتم دوره سفارش',
                'verbose_name_plural': 'آیتم\u200cهای دوره سفارش',
                'unique_together': {('order', 'course')},
            },
        ),
    ]
