# Generated by Django 5.2.1 on 2025-07-17 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام دپارتمان دوره')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'دپارتمان دوره',
                'verbose_name_plural': 'دپارتمان\u200c های دوره',
            },
        ),
        migrations.CreateModel(
            name='CourseTicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='Tickets/course_ticket_attachments/', verbose_name='فایل')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
            ],
            options={
                'verbose_name': 'پیوست تیکت دوره',
                'verbose_name_plural': 'پیوست\u200c های تیکت دوره',
            },
        ),
        migrations.CreateModel(
            name='CourseTicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'پیام تیکت دوره',
                'verbose_name_plural': 'پیام\u200c های تیکت دوره',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام دپارتمان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'دپارتمان',
                'verbose_name_plural': 'دپارتمان \u200cها',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='موضوع')),
                ('priority', models.CharField(choices=[('LW', 'کم'), ('ME', 'متوسط'), ('HG', 'بالا'), ('UR', 'اضطراری')], default='LW', max_length=10, verbose_name='اولویت')),
                ('status', models.CharField(choices=[('NW', 'جدید'), ('AD', 'پاسخ داده شده'), ('IN', 'درحال بررسی'), ('CL', 'بسته شده')], default='NW', max_length=10, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بسته شدن')),
            ],
            options={
                'verbose_name': 'تیکت',
                'verbose_name_plural': 'تیکت\u200c ها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='Tickets/ticket_attachments/', verbose_name='فایل')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
            ],
            options={
                'verbose_name': 'پیوست تیکت',
                'verbose_name_plural': 'پیوست\u200c های تیکت',
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'پیام تیکت',
                'verbose_name_plural': 'پیام\u200c های تیکت',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='موضوع')),
                ('priority', models.CharField(choices=[('LW', 'کم'), ('ME', 'متوسط'), ('HG', 'بالا'), ('UR', 'اضطراری')], default='LW', max_length=10, verbose_name='اولویت')),
                ('status', models.CharField(choices=[('NW', 'جدید'), ('AD', 'پاسخ داده شده'), ('IN', 'درحال بررسی'), ('CL', 'بسته شده')], default='NW', max_length=10, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بسته شدن')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_tickets', to='Courses.course', verbose_name='دوره مرتبط')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tickets.coursedepartment', verbose_name='دپارتمان دوره')),
            ],
            options={
                'verbose_name': 'تیکت دوره',
                'verbose_name_plural': 'تیکت\u200c های دوره',
                'ordering': ['-created_at'],
            },
        ),
    ]
