# Generated by Django 5.2.1 on 2025-06-05 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0004_ticketattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketattachment',
            name='file',
            field=models.FileField(upload_to='Tickets/ticket_attachments/', verbose_name='فایل'),
        ),
    ]
