# Generated by Django 5.2.1 on 2025-06-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0005_alter_ticketattachment_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام دپارتمان دوره')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'دپارتمان دوره',
                'verbose_name_plural': 'دپارتمان\u200c های دوره',
            },
        ),
    ]
