# Generated by Django 5.2.1 on 2025-06-26 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0008_courseticketmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='Tickets/course_ticket_attachments/', verbose_name='فایل')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_attachments', to='Tickets.courseticketmessage', verbose_name='پیام تیکت دوره')),
            ],
            options={
                'verbose_name': 'پیوست تیکت دوره',
                'verbose_name_plural': 'پیوست\u200c های تیکت دوره',
            },
        ),
    ]
